apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jboss-example-pvc
  namespace: jboss-example
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-filesystem
