apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: jboss-image-pipeline-run
spec:
  pipelineRef:
    name: jboss-image-config-pipeline
  serviceAccountName: pipeline
  params:
    - name: URL
      value: https://github.com/salanisor/openshift-pipelines.git
    - name: IMAGE
      value: 'quay.apps.ocp4.example.com/jboss-example'
    - name: image-tag
      value: '001'
    - name: TLS_VERIFY
      value: "false"
  workspaces:
    # - name: workspace-jboss
    #   volumeClaimTemplate:
    #     spec:
    #       storageClassName: local-filesystem
    #       accessModes:
    #         - ReadWriteOnce
    #       resources:
    #         requests:
    #           storage: 1Gi
    # - name: workspace-jboss
    #   emptyDir: {}
  workspaces:
    - name: workspace-jboss
      persistentVolumeClaim:
        claimName: jboss-example-pvc