apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: deploy-run
  namespace: pipelines
spec:
  pipelineRef:
    name: deploy-pipeline
  serviceAccountName: pipeline
  params:
    - name: DOCKERFILE
      value: 'Containerfile-SELinux'
    - name: URL
      value: https://github.com/salanisor/openshift-pipelines.git
    - name: git-revision
      value: learn
    - name: SCRIPT
      value: 'oc apply -f manifests/'
  workspaces:
    - name: workspace-build
      persistentVolumeClaim:
        claimName: pipeline-pvc
  taskRunSpecs:
    - pipelineTaskName: deploy-to-namespace
      stepSpecs:
        - name: oc
          computeResources:
            requests:
              memory: "64Mi"
              cpu: "250m"
          image: registry.redhat.io/openshift4/ose-cli:latest