apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: base-image-config-pipeline
  namespace: pipelines
spec:
  workspaces:
    - name: workspace-build
      description: Shared workspace for source code and build artifacts
  
  params:
    - name: SCRIPT
      type: string
      default: |
        echo "Deployment script placeholder"
        echo "Built image: $(params.IMAGE):$(params.image-tag)"
        oc version
      description: Script to execute in the deploy task
    - name: image-tag
      type: string
      description: Version of the newly built image
    - name: URL
      type: string
      description: URL of the git repo for the code of deployment
      default: https://github.com/salanisor/openshift-pipelines.git
    - name: IMAGE
      type: string
      description: Image to be built from the code
      default: quay.apps.ocp4.keights.org/openshift/base-images:ubi8-minimal-latest
    - name: git-revision
      type: string
      description: Revision to be used from repo of the code for deployment
      default: main
    - name: TLS_VERIFY
      type: string
      description: Sets the TLS verification flag, `true` is recommended
      default: "false"
    - name: DOCKERFILE
      type: string
      description: Path to the Dockerfile to build
      default: Dockerfile
    - name: BUILDER_IMAGE
      type: string
      description: The image used to build the container
      default: registry.redhat.io/rhel9/buildah
    - name: CONTEXT
      type: string
      description: Path to the directory to use as context
      default: "."
  
  tasks:
    - name: git-clone
      taskRef:
        resolver: cluster
        params:
          - name: namespace
            value: openshift-pipelines
          - name: kind
            value: task
          - name: name
            value: git-clone
      params:
        - name: URL
          value: $(params.URL)
        - name: SUBDIRECTORY
          value: ""
        - name: DELETE_EXISTING
          value: "true"
        - name: REVISION
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: workspace-build
    
    - name: buildah-bud-and-push
      runAfter:
        - git-clone
      taskRef:
        resolver: cluster
        params:
          - name: namespace
            value: openshift-pipelines
          - name: kind
            value: task
          - name: name
            value: buildah
      params:
        - name: IMAGE
          value: $(params.IMAGE):$(params.image-tag)
        - name: BUILDER_IMAGE
          value: $(params.BUILDER_IMAGE)
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: $(params.DOCKERFILE)
        - name: CONTEXT
          value: $(params.CONTEXT)
        - name: TLS_VERIFY
          value: $(params.TLS_VERIFY)
        - name: FORMAT
          value: oci
        - name: BUILD_EXTRA_ARGS
          value: ''
        - name: PUSH_EXTRA_ARGS
          value: ''
        - name: SKIP_PUSH
          value: 'false'
      workspaces:
        - name: source
          workspace: workspace-build
    
    - name: deploy-to-namespace
      runAfter:
        - buildah-bud-and-push
      taskRef:
        resolver: cluster
        params:
          - name: namespace
            value: openshift-pipelines
          - name: kind
            value: task
          - name: name
            value: openshift-client
      params:
        - name: SCRIPT
          value: $(params.SCRIPT)
      workspaces:
        - name: manifest_dir
          workspace: workspace-build
